### PR TITLE
version 1.5.0, add mukhery as maintainer

### PR DESCRIPTION
**Pull request by mukhery**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mukhery** [comment]
@conda-forge-admin, please rerender

**Comment by mukhery** [comment]
@benhuff @mxr-conda @oblute @rluria14 can one of you merge this please?

**Comment by mukhery** [comment]
@conda-forge/core can you guys merge this please so that I can help maintain this feedstock?

**Comment by beckermr** [comment]
@conda-forge-admin update team

**Comment by mukhery** [comment]
> @conda-forge-admin update team

@beckermr was something supposed to happen?

**Comment by beckermr** [comment]
Ack I had the wrong pr. Let me look at this one too.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Pull request merged**
